### ISSUE TITLE
Mail stuff complaints from an admin from a university. bounce to bounce reply

### ISSUE THREAD

**Issue by Sliverriver** [foodsharing-dev/foodsharing-infrastructure#1]
I got this mail from a university -where we some students registered with foodsharing. 
what happens is : 
1 . we send a newsletter to the address of the student at the university that no longer exists.
2. the mailgate from them sends an undelivered to our envelope sender
3. because of autoreply noreply@uni-mainz.de there is an reply back to the mailgate that the noreply address is not rechable.

he has the piont of view that something is wrongly configured from our sie, because we should never send a bounce to a bounce

https://de.wikipedia.org/wiki/Bounce_Message

he asks kindly if we cold fix this.

Hallo Kristijan,

sorry, da hab ich nicht richtig aufgepasst. Es ist wohl nicht so, dass unsere Postmaster-Adresse auf eurer Liste steht.

Stattdessen ist folgendes passiert:

1. Ihr schickt euren Newsletter an Uni-Mainz-Adressen, die nicht mehr existieren.
2. Unser Mailgate schickt einen Unzustellbar-Bounce an den Envelope Sender.
3. Durch ein Autoreply schreibt noreply@uni-mainz.de an unser Mailgate zurück (From-Adresse), dass die Noreply-Adresse nicht erreichbar ist.

Aus meiner Sicht ist da bei euch was falsch konfiguriert. Ihr solltet niemals einen Bounce auf einen Bounce (Punkt 3) zurücksenden.

https://de.wikipedia.org/wiki/Bounce_Message

Könntet Ihr das korrigieren?

Schöne Grüße

Andreas Rosendahl

20.04.2017 21:08 - info schrieb:

Hallo zusammen,

wir haben keinen Nutzer der „postmaster@uni-mainz.de
<mailto:postmaster@uni-mainz.de>“ als e-mail Adresse benutzt.

Wir haben 39 Nutzer mit 'Uni-mainz.de‘  in der e-mail addresse

Können sie nähere angaben dazu machen welche e-mail addresse es ist die bei ihnen
nicht mehr gültig ist ?

viele grüße

Kristijan

Am 20.04.2017 um 19:25 schrieb info <info@foodsharing.de>:

Hallo ,

ich leite es an die IT weiter,
wir prüfen ob jemand sich über die Adresse „postmaster@uni-mainz.de <mailto:postmaster@uni-mainz.de>“ als Benutzer angemeldet hat. 

viele grüße

Kristijan

Am 20.04.2017 um 11:26 schrieb ZDV Postmaster <postmaster@uni-mainz.de <mailto:postmaster@uni-mainz.de>>:

Bitte sofort unsere Postmaster-Adresse von eurer Liste nehmen.
Danke

19.04.2017 21:05 - noreply@lebensmittelretten.de <mailto:noreply@lebensmittelretten.de> schrieb:

Auf diese E-Mail kannst Du nicht antworten,

Solltest Du auf eine Nachricht antworten wollen, dann benutze den Antworten Button
in der E-Mail die Du erhalten hast.

herzlich sonnige Grüße,
Dein lebensmittelretten Team

**Comment by NerdyProjects** [comment]
I did not even know about that auto responder :-)

So it was an auto responder configured at greensta for noreply@lebensmittelretten.de sending that text. Technically, that is fine. Although I get his complaint and as greensta does not offer better filtering for the auto responder I disabled it completely.

BTW kristijan please do not put private information like emailadresses and names here... I edited/removed them.
